In [8]:
import numpy as np
np.__version__

'1.24.1'

In [9]:
# criando arrays
lista = [1,2,3]
a = np.array(lista)
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [10]:
# criando arrays
a = np.array([1,2,3])
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [11]:
# criando arrays com tipos de dados diferentes
lista = [1,2,"Mentorama",3,4]
a = np.array(lista)
print(a)
type(a)

['1' '2' 'Mentorama' '3' '4']


numpy.ndarray

In [12]:
# criando arrays multidimensionais de nnumeros inteiros (matriz)
b = np.array([[1,2,3], [3,4,5]])
print(b)
type(b)

[[1 2 3]
 [3 4 5]]


numpy.ndarray

In [13]:
# o comando shape retorna uma tupla com as dimensoes do objeto 'a' - tem 5 elementos
a.shape

(5,)

In [14]:
# o comando shape retorna uma tupla com as dimmensoes do objeto 'b' - tem 2 linhas e 3 colunas
b.shape

(2, 3)

In [15]:
# o comando ndim retorna um numero indicando a quantidade de dimensoes do objeto 'b' - 2 dimensoes
b.ndim

2

In [16]:
# criando arrays multidimensionais de numeros floats
c = np.array([[1.1,2,3], [3,4,5]])
print(c)
type(c)

[[1.1 2.  3. ]
 [3.  4.  5. ]]


numpy.ndarray

In [17]:
# criando arrays com apenas numeros zeros automaticamente
zeros_arrays = np.zeros((2,3)) # 2 linhas e 3 colunas
print(zeros_arrays)
print(f'O Formato do array sao: {zeros_arrays.shape}')
print(f'Quantidade de dimensoes dos arrays: {zeros_arrays.ndim}')

[[0. 0. 0.]
 [0. 0. 0.]]
O Formato do array sao: (2, 3)
Quantidade de dimensoes dos arrays: 2


In [18]:
# criando arrays com us numeros automaticamente
# 5 linha e 5 colunas
ones_array = np.ones((5,5), dtype=np.int32) # specifying dtype
print(ones_array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
# criando uma matriz identidade (Numeros 1 a diagonal e zero o restante da matriz
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# cria um array no intervalo definido, com numeros uniformemente espacados
np.linspace(0,10,10) #  de zero a 10

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [21]:
# crie uma matriz / array no formato fornecido, preenchido com amostras aleatorias de uma distribuicao uniforme [0, 1] intervalo entre 0 e 1
a = np.random.rand(5)
print(a)

[0.73156295 0.53179659 0.80692204 0.78166245 0.26544462]


In [22]:
a = np.random.rand(5)*100
print(a)

[59.54595585 72.6259281  42.7657666  48.79888665  1.17865165]


In [23]:
a = np.random.rand(5,2,3) #cubo
print(a)

[[[0.71712157 0.3175593  0.81920713]
  [0.14677426 0.9534394  0.25256494]]

 [[0.61566877 0.48690248 0.48102951]
  [0.71305972 0.09218302 0.75261579]]

 [[0.69242141 0.03629025 0.96657293]
  [0.27618027 0.94009772 0.57609867]]

 [[0.04435569 0.00487567 0.0327814 ]
  [0.0075154  0.71980927 0.62295168]]

 [[0.09412823 0.81569145 0.83776476]
  [0.66109682 0.56168774 0.86393382]]]


In [24]:
# cria um array com 18 elementos
a = np.arange(18)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [25]:
# cria um array no intervalo de 0 a 30 com elementos de 3
b = np.arange(0, 30, 3)
print(b)

[ 0  3  6  9 12 15 18 21 24 27]


In [27]:
# INDEXACAO E FATIAMENTO DE ARRAYS
# Acessando um elemento na posicao 1 do array criado
b[1]

3

In [28]:
# acessando um intervalo definido de valores do array
b[2:6]

array([ 6,  9, 12, 15])

In [29]:
# acessando todos os valores a partir do indice estipulado
b[:5]

array([ 0,  3,  6,  9, 12])

In [30]:
b[2:]

array([ 6,  9, 12, 15, 18, 21, 24, 27])

In [31]:
# atribuindo valores em uma determinada  posicao do array
b[2]=100
print(b)

[  0   3 100   9  12  15  18  21  24  27]


In [32]:
# atribuindo novos valores no intervalo de 0 a 50 no formato de matriz com 5 linhas e 10 colunas
b = np.arange(50).reshape(5, 10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [33]:
# verificando a forma criada
b.shape

(5, 10)

In [34]:
# extraindo dados de um intervalo especifico (primeiro colchete -> linhas e segundo colchete -> colunas
b[:4] [:]  #  até a posicao 4 das colunas e [:] todos os itens da linha

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

# OPERACOES MATEMATICAS
Consultar documentacao do Matplolib para verificar todas as possibilidades

In [37]:
# criando umm conjunto de numeros aleatorios
np.random.seed(42)  # 42 nummeros aleatorios
# criando arrays usando o modulo randomico do numpy
a = np.random.randint(1,3,5)
b = np.random.randint(0,10,5)

In [38]:
print(a)
print(b)

[1 2 1 1 1]
[7 4 6 9 2]


In [39]:
# subtracao
np.subtract(b,a)

array([6, 2, 5, 8, 1])

In [40]:
# adicao
np.add(b,a)

array([ 8,  6,  7, 10,  3])

In [42]:
# divisao
np.divide(a,b)

array([0.14285714, 0.5       , 0.16666667, 0.11111111, 0.5       ])

In [43]:
# multiplicacao
np.multiply(a,b)

array([7, 8, 6, 9, 2])

In [44]:
# exponencial
np.exp(a)

array([2.71828183, 7.3890561 , 2.71828183, 2.71828183, 2.71828183])

In [45]:
# raiz quadrada
np.sqrt(a)

array([1.        , 1.41421356, 1.        , 1.        , 1.        ])

In [46]:
# computar o seno
np.sin(a)

array([0.84147098, 0.90929743, 0.84147098, 0.84147098, 0.84147098])

In [47]:
# logaritmos
np.log(a)

array([0.        , 0.69314718, 0.        , 0.        , 0.        ])

In [48]:
np.log2(a)

array([0., 1., 0., 0., 0.])

In [49]:
# como arrendodar uma matriz
np.random.seed(42)
a = np.random.rand(5)
print(a)
np.around(a)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


array([0., 1., 1., 1., 0.])